api/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('v1/clientes/', Clientelist.as_view(), name='cliente_list'),
    path('v1/clientes/<str:codigo_cliente>', ClienteDetalle.as_view(), name='cliente_detalle'),

    path('v1/producto/',Productolist.as_view(), name='producto_list'),
    path('v1/producto/<str:pk>',ProductoDetalle.as_view(), name='producto_detalle'),
]

tloz/urls.py
from django.contrib import admin
from django.db.models import enums

from django.urls import path, include


urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')),
    path('impa/', include(('impa.urls','impa'), namespace='impa')),
    path('link/', include(('link.urls','link'), namespace='link')),
    path('zelda/', include(('zelda.urls','zelda'), namespace='zelda')),
    path('imphija/', include(('imphija.urls','imphija'), namespace='imphija')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('tests/', include(('tests.urls','tests'), namespace='tests')),
   
    path('api/', include(('api.urls','api'), namespace='api')),
    path('admin/', admin.site.urls),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Transportes JR</title>
        
        {% load static %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
        
        
        {% block css %}
        <link rel="stylesheet" href="{% static 'base/css/estilo.css' %}">
        <link rel="stylesheet" href="{% static 'base/css/estiloo.css' %}">
        {% comment %} <link rel="stylesheet" href="{% static 'base/css/hija.css' %}"> {% endcomment %}
        <link rel="stylesheet" href="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        {% comment %} <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"> {% endcomment %}
        {% endblock %}
        <script src="{% static  'base/js/msj.js' %}"></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js'></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </head>
    <body>

        <div id="navbar">
            <div class="elements">
                <div class="navigation">
                    <ul>
                      <li class="list test">
                          <a href="#">
                            <span class="icon"><i class="fas fa-home"></i></span>
                            <ul class="despliegue">
                              <li><a href="{% url 'tests:test' %}"> <i></i> Test </a></li>
                            </ul>
                          </a>
                      </li>

                      <li class="list home">
                        <a href="#">
                          <span class="icon"><i class="fas fa-warehouse"></i></span>
                          <ul class="despliegue">
                            <li><a href="{% url 'link:ingreso_bodega' %}"> <i></i> Ingreso Bodega</a></li>
                            <li><a href="#">Salida Bodega </a></li>
                            <li><a href="#">Reimprimir Manifiesto</a></li>
                            <li><a href="{% url 'link:consulta' %}">Consulta de Guías</a></li>
                          </ul>
                        </a>
                      </li>
                      <li class="list file">
                        <a href="#">
                          <span class="icon"><i class="fas fa-file"></i></span>
                          <ul class="despliegue">
                            <li><a href="{% url 'link:ingreso_new' %}"> <i></i> Ingreso de Guías</a></li>
                            <li><a href="#">Modificación de Guías</a></li>
                            <li><a href="#">Emilinación de Guías</a></li>
                            <li><a href="{% url 'link:consulta' %}">Consulta de Guías</a></li>
                          </ul>
                        </a>
                      </li>
                      <li class="list camera">
                        <a href="#">
                          <span class="icon"><i class="fas fa-camera"></i></span>
                          <ul class="despliegue">
                            {% comment %} <li><a href="{% url 'rcp:ingreso_rcp' %}"> <i></i> Ingreso Recepcion</a></li> {% endcomment %}
                            <li><a href="{% url 'link:correlativo_list' %}">Asignar Correlativo</a></li>
                            <li><a href="#">Emilinación de Guías</a></li>
                            <li><a href="{% url 'link:consulta' %}">Consulta de Guías</a></li>
                          </ul>
                        </a>
                      </li>
                      <li class="list">
                        <a href="#">
                          <span class="icon"><i class="fas fa-comment"></i></span>
                        </a>
                      </li>
                      <li class="list">
                        <a href="#">
                          <span class="icon"><i class="fas fa-chart-bar"></i></span>
                        </a>
                      </li>
                      <li class="list cogs">
                        <a href="#">
                          <span class="icon"><i class="fas fa-cogs"></i></span>
                          <ul class="despliegue">
                            <li><a href="{% url 'link:departamento_list' %}"><i class="fas fa-plus"></i>&nbsp; Departamento</a></li>
                            <li><a href="{% url 'link:municipio_list' %}"><i class="fas fa-plus"></i>&nbsp; Municipio</a></li>
                            <li><a href="{% url 'link:piloto_list' %}"> <i class="fas fa-plus"></i>&nbsp; Pilotos</a></li>
                            <li><a href="{% url 'link:ruta_list' %}"> <i class="fas fa-plus"></i>&nbsp; Rutas</a></li>
                            <li><a href="{% url 'link:tarifario_list' %}"> <i class="fas fa-plus"></i>&nbsp; Tarifario </a></li>
                            <li><a href="{% url 'link:vendedor_list' %}"> <i class="fas fa-plus"></i>&nbsp; Vendedor</a></li>
                            <li><a href="{% url 'link:cliente_list' %}"> <i class="fas fa-plus"></i>&nbsp; Cliente</a></li>
                            <li><a href="#"> <i class="fas fa-plus"></i>&nbsp; Boletas de Deposito</a></li>
                          </ul>
                        </a>
                      </li>
                      <li class="list combu">
                        <a href="#">
                          <span class="icon"><i class="fas fa-box"></i></span>
                          <ul class="despliegue">
                            <li>
                              <a href="{% url 'zelda:registro_list' %}" id="left" onmouseover="seis()"> <i class="fas fa-gas-pump"></i> Listado de Facturas </a>
                            </li>
                          </ul>
                        </a>
                      </li>
                   <div class="indicator"></div>
                    </ul>
                   </div> 
            </div>
            <div class="user">
              {% if user.is_authenticated %}
              <span id="userName">{{ user.username }}</span>&nbsp;&nbsp;<a title="Salir de la sesión" href="{% url 'bases:logout' %}"><i class="fas fa-sign-out-alt"></i></a>
              {% else %}
              <span id="userName"><a href="{% url 'bases:login' %}">Iniciar Sesión</a></span>&nbsp;&nbsp;<i class="fas fa-user-alt"></i>
              <span id="userName"><a href="{% url 'link:registro' %}">Registrate</a></span>&nbsp;&nbsp;<i class="fas fa-user-alt"></i>
              {% endif %}
            </div>
         </div>
        <section id="home"></section>
        <script>
        //  Añade el active al icono que se esté clickeando
        const list=document.querySelectorAll(".list");
        function activeLink(){
            list.forEach((item)=>
              item.classList.remove("active")
            );
            this.classList.add("active");
        }
        list.forEach((item)=>
          item.addEventListener("click",activeLink)
        );
        
        // Esconde y muestra el navbar
        $(document).ready(function(){
            // Si el mouse está sobre el nabvar, se observan los elementos
            $("#navbar").mouseover(function(){
                $(".navigation > ul >li").css("opacity", "1");
                $(".indicator").css("opacity", "1");
                $(".navigation > ul >li").css("visibility", "visible");
                $(".indicator").css("visibility", "visible");
                $("#navbar > .user > #userName").css("visibility", "visible");
                $("#navbar > .user > #userName").css("opacity", "1");
            });
            // Si el mouse no está sobre el nabvar, no se observan los elementos
            $("#navbar").mouseout(function(){
                $(".navigation > ul >li").css("opacity", "0");
                $(".indicator").css("opacity", "0");
                $(".navigation > ul >li").css("visibility", "hidden");
                $(".indicator").css("visibility", "hidden");
                $("#navbar > .user > #userName").css("visibility", "hidden");
                $("#navbar > .user > #userName").css("opacity", "0");
            });
        });
        // Funcion para el .list que llevará un despliegue
        $("li.list.home").on("click",function() {
          // Se agrega la clase .des1 cuando se clickea en el list con despliegue
          document.querySelector("li.list.home").classList.toggle("des1");
        });
        $("li.list.cogs").on("click",function() {
          // Se agrega la clase .des1 cuando se clickea en el list con despliegue
          document.querySelector("li.list.cogs").classList.toggle("des1");
        });
        $("li.list.file").on("click",function() {
          // Se agrega la clase .des1 cuando se clickea en el list con despliegue
          document.querySelector("li.list.file").classList.toggle("des1");
        });
        $("li.list.combu").on("click",function() {
          // Se agrega la clase .des1 cuando se clickea en el list con despliegue
          document.querySelector("li.list.combu").classList.toggle("des1");
        });
        $("li.list.camera").on("click",function() {
          // Se agrega la clase .des1 cuando se clickea en el list con despliegue
          document.querySelector("li.list.camera").classList.toggle("des1");
        });
        $("li.list.test").on("click",function() {
          // Se agrega la clase .des1 cuando se clickea en el list con despliegue
          document.querySelector("li.list.test").classList.toggle("des1");
        });
        // Se elimina la clase .des1 cuando se clickea fuera de él
        $(document).on("click",function(e) {
          const cogs = $("li.list.cogs");
          const home = $("li.list.home");
          const file = $("li.list.file");
          const combu = $("li.list.combu");
          const camera = $("li.list.camera");
          const test = $("li.list.test");

          if (!cogs.is(e.target) && cogs.has(e.target).length === 0) { 
            document.querySelector("li.list.cogs").classList.remove("des1");
          }
          if(!home.is(e.target) && home.has(e.target).length === 0){
            document.querySelector("li.list.home").classList.remove("des1");
          }
          if(!combu.is(e.target) && combu.has(e.target).length === 0){
            document.querySelector("li.list.combu").classList.remove("des1");
          }
          if(!file.is(e.target) && file.has(e.target).length === 0){
            document.querySelector("li.list.file").classList.remove("des1");
          }
          if(!camera.is(e.target) && camera.has(e.target).length === 0){
            document.querySelector("li.list.camera").classList.remove("des1");
          }
          if(!test.is(e.target) && test.has(e.target).length === 0){
            document.querySelector("li.list.test").classList.remove("des1");
          }
        });
        // Se elimina la clase .des1 al ocultarse el navbar
/*         $("#navbar").on("mouseleave",function(e) {
          const container = $("li.list.cogs");

          if (!container.is(e.target) && container.has(e.target).length === 0) { 
            document.querySelector("li.list.cogs").classList.remove("des1");
          }
        }); */
        </script>
    </div>
    
    <div class="modal fade" id="popup"></div>
   

        {% block contenido %}
        {% endblock %}
    
        
<!-- Bootstrap core JavaScript-->
<script src="{% static  'base/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static  'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static  'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static  'base/js/sb-admin-2.min.js' %}"></script>


<!-- Page level plugins -->
<script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<script src="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>  

<script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table-locale-all.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>



<script src="{% static  'base/js/jquery.chained.min.js' %}"></script>


{% block js %} {% endblock %}
{% block control_modal %}
<script>
    function abrir_modal(url)
    {

      $("#popup").load(url, function(){
        $(this).modal({
          backdrop:'static',
          keyboard: false
        })
        $(this).modal('show');
      });
      return false;
    }

    function cerrar_modal()
    {
      $('#popup').modal('hide');
      return false;
    }   
</script>
{% endblock %}


    </body>
</html>